#!/usr/bin/env bash
# web servers are software serving HTML pages
# nginx is a web server software - Software Load Balancer
sudo apt-get update
sudo apt-get -y install nginx
sudo echo 'Holberton School' > /var/www/html/index.html
sudo service nginx start
