#!/usr/bin/env bash
# Redirection to youtube
new_string = "\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
find = $(grep "redirect_me" /etc/nginx/sites-available/default)
if [[ -z find ]]; then
	sed -i "49i $new_string" /etc/nginx/sites-available/default
	sudo service nginx restart
fi
