#!/usr/bin/env bash
# NGINX server config with 404 and redirection sites
apt-get -y update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/server_name -;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sed -i "/redirect_me/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
service nginx restart
