#!/usr/bin/env bash
# meme script, do not execute if you love your machine

touch holbertonscript.pid
echo >> holbertonscript.pid
sudo mv holbertonscript.pid /var/run/
while true; do
      trap "echo I hate the kill command && sudo rm /var/run/holbertonscript.pid && exit" SIGTERM SIGQUIT
      trap "echo Y U no love me?!" SIGINT
      echo "To infinity and beyond"
done
